name: Horizons
description: Horizons template for Jekyll

author:
  name      : 'Quantum development group'
  #email    : hi@nandomoreira.me
  url       : "https://quantchemdev.github.io" # the base hostname & protocol for your site
  baseurl   : '/' #subpath of the web
  #facebook : http://facebook.com/fernando.dev
  #twitter  : http://twitter.com/nandomoreirame

github: https://github.com/quantchemdev
#disqus_shortname: "fernandomoreira"
#google_analytics: UA-52446115-1
sass:
  sass_dir: assets/css
  
# Explicitly turn off the old code
paginate: nil
paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 4
  offset: 2
  permalink: '/blog/page:num/'
  title: ':title - page :num of :max'
  limit: 5
  sort_field: 'date'
  sort_reverse: true
